failing-DMSO-right:
  UMAP0: [6, 7]
  UMAP1: [3.75, 5]
  Random state: 30
  composite_save_path: composite_image_failing_DMSO_right.tiff
  crop_save_path: cell_cropped_failing_DMSO_right.tiff

healthy-DMSO-top:
  UMAP0: [0.5, 2]
  UMAP1: [8.5, 9]
  Random state: 15
  composite_save_path: composite_image_healthy_DMSO_top.tiff
  crop_save_path: cell_cropped_healthy_DMSO_top.tiff

healthy-DMSO-top1:
  UMAP0: [0.5, 2]
  UMAP1: [8.5, 9]
  Random state: 37  
  composite_save_path: composite_image_healthy_DMSO_top1.tiff
  crop_save_path: cell_cropped_healthy_DMSO_top1.tiff

healthy-DMSO-top2:
  UMAP0: [0.5, 2]
  UMAP1: [8.5, 9]
  Random state: 56 
  composite_save_path: composite_image_healthy_DMSO_top2.tiff
  crop_save_path: cell_cropped_healthy_DMSO_top2.tiff

failing-drug_x-right:
  UMAP0: [6, 7.5]
  UMAP1: [3.75, 4.5]
  Random state: 15
  composite_save_path: composite_image_failing_drug_x_right.tiff
  crop_save_path: cell_cropped_failing_drug_x_right.tiff

healthy-DMSO-right:
  UMAP0: [6, 7.5]
  UMAP1: [3.5, 4.5]
  Random state: 25
  composite_save_path: composite_image_healthy_DMSO_right.tiff
  crop_save_path: cell_cropped_healthy_DMSO_right.tiff

failing-drug_x-left:
  UMAP0: [-1, 0]
  UMAP1: [6.25, 7.5]
  Random state: 30
  composite_save_path: composite_image_failing_drug_x_left.tiff
  crop_save_path: cell_cropped_failing_drug_x_left.tiff

failing-drug_x-left1:
  UMAP0: [-1, 0]
  UMAP1: [6.25, 7.5]
  Random state: 8
  composite_save_path: composite_image_failing_drug_x_left1.tiff
  crop_save_path: cell_cropped_failing_drug_x_left1.tiff

failing-drug_x-left2:
  UMAP0: [-1, 0]
  UMAP1: [6.25, 7.5]
  Random state: 75
  composite_save_path: composite_image_failing_drug_x_left2.tiff
  crop_save_path: cell_cropped_failing_drug_x_left2.tiff
  
failing-DMSO-left:
  UMAP0: [-3, 0]
  UMAP1: [2.5, 5]
  Random state: 30
  composite_save_path: composite_image_failing_DMSO_left.tiff
  crop_save_path: cell_cropped_failing_DMSO_left.tiff

failing-DMSO-left1:
  UMAP0: [-3, 0]
  UMAP1: [2.5, 5]
  Random state: 65
  composite_save_path: composite_image_failing_DMSO_left1.tiff
  crop_save_path: cell_cropped_failing_DMSO_left1.tiff

failing-DMSO-left2:
  UMAP0: [-3, 0]
  UMAP1: [2.5, 5]
  Random state: 12
  composite_save_path: composite_image_failing_DMSO_left2.tiff
  crop_save_path: cell_cropped_failing_DMSO_left2.tiff

failing-DMSO-bottom:
  UMAP0: [-1, 1]
  UMAP1: [-2, 1]
  Random state: 30
  composite_save_path: composite_image_failing_DMSO_bottom.tiff
  crop_save_path: cell_cropped_failing_DMSO_bottom.tiff

failing-drug_x-bottom:
  UMAP0: [-1, 1]
  UMAP1: [-2, 1]
  Random state: 30
  composite_save_path: composite_image_failing_drug_x_bottom.tiff
  crop_save_path: cell_cropped_failing_drug_x_bottom.tiff

healthy-DMSO-bottom:
  UMAP0: [-1, 1]
  UMAP1: [-2, 1]
  Random state: 25
  composite_save_path: composite_image_healthy_DMSO_bottom.tiff
  crop_save_path: cell_cropped_healthy_DMSO_bottom.tiff
